module Exact
  class Item < Base
    include ActiveModel::Model
    include Virtus.model

    EXACT_SERVICE = 'logistics'
    EXACT_GUID    = 'ID'

    attribute :IsSerialNumberItem,      String
    attribute :IsBatchNumberItem,       String
    attribute :Class_01,                String
    attribute :Class_02,                String
    attribute :Class_03,                String
    attribute :Class_04,                String
    attribute :Class_05,                String
    attribute :Class_06,                String
    attribute :Class_07,                String
    attribute :Class_08,                String
    attribute :Class_09,                String
    attribute :Class_10,                String
    attribute :Code,                    String
    attribute :CopyRemarks,             String
    attribute :CostPriceCurrency,       String
    attribute :CostPriceNew,            String
    attribute :CostPriceStandard,       String
    attribute :Created,                 DateTime
    attribute :CreatorFullName,         String
    attribute :Creator,                 String
    attribute :Description,             String
    attribute :Division,                String
    attribute :EndDate,                 DateTime
    attribute :ExtraDescription,        String
    attribute :FreeBoolField_01,        String
    attribute :FreeBoolField_02,        String
    attribute :FreeBoolField_03,        String
    attribute :FreeBoolField_04,        String
    attribute :FreeBoolField_05,        String
    attribute :FreeDateField_01,        DateTime
    attribute :FreeDateField_02,        DateTime
    attribute :FreeDateField_03,        DateTime
    attribute :FreeDateField_04,        DateTime
    attribute :FreeDateField_05,        DateTime
    attribute :FreeNumberField_01,      String
    attribute :FreeNumberField_02,      String
    attribute :FreeNumberField_03,      String
    attribute :FreeNumberField_04,      String
    attribute :FreeNumberField_05,      String
    attribute :FreeNumberField_06,      String
    attribute :FreeNumberField_07,      String
    attribute :FreeNumberField_08,      String
    attribute :FreeTextField_01,        String
    attribute :FreeTextField_02,        String
    attribute :FreeTextField_03,        String
    attribute :FreeTextField_04,        String
    attribute :FreeTextField_05,        String
    attribute :FreeTextField_06,        String
    attribute :FreeTextField_07,        String
    attribute :FreeTextField_08,        String
    attribute :FreeTextField_09,        String
    attribute :FreeTextField_10,        String
    attribute :GLCostsCode,             String
    attribute :GLCostsDescription,      String
    attribute :GLCosts,                 String
    attribute :GLRevenueCode,           String
    attribute :GLRevenueDescription,    String
    attribute :GLRevenue,               String
    attribute :GLStockCode,             String
    attribute :GLStockDescription,      String
    attribute :GLStock,                 String
    attribute :ID,                      String
    attribute :IsBatchItem,             String
    attribute :IsFractionAllowedItem,   String
    attribute :IsMakeItem,              String
    attribute :IsNewContract,           String
    attribute :IsOnDemandItem,          String
    attribute :IsPackageItem,           String
    attribute :IsPurchaseItem,          String
    attribute :IsRegistrationCodeItem,  String
    attribute :IsSalesItem,             String
    attribute :IsSerialItem,            String
    attribute :IsStockItem,             String
    attribute :IsSubcontractedItem,     String
    attribute :IsTime,                  String
    attribute :IsWebshopItem,           String
    attribute :ItemGroupCode,           String
    attribute :ItemGroupDescription,    String
    attribute :ItemGroup,               String
    attribute :Modified,                DateTime
    attribute :ModifierFullName,        String
    attribute :Modifier,                String
    attribute :Notes,                   String
    attribute :SalesVatCodeDescription, String
    attribute :SalesVatCode,            String
    attribute :SearchCode,              String
    attribute :SecurityLevel,           String
    attribute :StartDate,               DateTime
    attribute :Unit,                    String
    attribute :UnitDescription,         String
    attribute :NetWeight,               String
    attribute :NetWeightUnit,           String
    attribute :Barcode,                 String
    attribute :GrossWeight,             String
    attribute :IsTaxableItem,           String
    attribute :PictureName,             String
    attribute :PictureThumbnailUrl,     String
    attribute :PictureUrl,              String
    attribute :Stock,                   String
    attribute :UnitType,                String
  end
end
